"""tables and its relationships

Revision ID: f69ab4e9593e
Revises: 
Create Date: 2021-02-25 17:46:26.995560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f69ab4e9593e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bioactivity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cell_line', sa.String(length=50), nullable=True),
    sa.Column('compound', sa.String(length=50), nullable=True),
    sa.Column('ic50', sa.String(length=50), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('herb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('science_name', sa.String(length=50), nullable=True),
    sa.Column('vietnamese_name', sa.String(length=50), nullable=True),
    sa.Column('familia', sa.String(length=50), nullable=True),
    sa.Column('genus', sa.String(length=50), nullable=True),
    sa.Column('plant_image_path', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('substance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('structure_path', sa.String(length=200), nullable=True),
    sa.Column('brutto_formula', sa.String(length=50), nullable=True),
    sa.Column('mocecular_weight', sa.String(length=50), nullable=True),
    sa.Column('trivial_name', sa.String(length=50), nullable=True),
    sa.Column('specie', sa.String(length=50), nullable=True),
    sa.Column('synonyms', sa.String(length=50), nullable=True),
    sa.Column('part_of_plant', sa.String(length=50), nullable=True),
    sa.Column('cas_no', sa.String(length=50), nullable=True),
    sa.Column('toxicity_ld50', sa.String(length=50), nullable=True),
    sa.Column('ddsage', sa.String(length=50), nullable=True),
    sa.Column('systematic_name', sa.String(length=50), nullable=True),
    sa.Column('detail', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('herb_substances',
    sa.Column('herb_id', sa.Integer(), nullable=False),
    sa.Column('substances_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['herb_id'], ['herb.id'], ),
    sa.ForeignKeyConstraint(['substances_id'], ['substance.id'], ),
    sa.PrimaryKeyConstraint('herb_id', 'substances_id')
    )
    op.create_table('substances_bioactivity',
    sa.Column('substances_id', sa.Integer(), nullable=False),
    sa.Column('bioactivity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bioactivity_id'], ['bioactivity.id'], ),
    sa.ForeignKeyConstraint(['substances_id'], ['substance.id'], ),
    sa.PrimaryKeyConstraint('substances_id', 'bioactivity_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('substances_bioactivity')
    op.drop_table('herb_substances')
    op.drop_table('substance')
    op.drop_table('herb')
    op.drop_table('bioactivity')
    # ### end Alembic commands ###
